<!--
 * @Description: 
 * @Author: yangxia
 * @Date: 2022-03-07 14:51:39
-->

# window.onerror 和 window.addEventListener

`window.onerror` 的错误信息包含异常信息，出现异常的文件，行号以及异常对象。
`window.addEventListener('error')` 没有这么全

## 一. window.onerror

```javascript
window.onerror = function(message, source, lineno, colno, error) {
    // ... 
    return true; // 异常不继续冒泡，浏览器默认打印机制就会取消 
}
```

#### window.onerror存在的问题
##### 1、基于安全性考虑，无法捕捉到跨域的异常

但是我们生产的时候脚本都是存在cdn上的，都是跨域js，如何处理？

方法①：如果想通过onerror函数收集不同域的js错误，我们需要做两件事：
    （1）相关的js文件上加上Access-Control-Allow-Origin:*的response header
    （2）引用相关的js文件时加上crossorigin属性
    但是我后来发现很多cdn上的script并没有加上crossorigin属性，但是依然可以发错误详情，原因可以看下文：[参考链接](https://blog.sentry.io/2016/05/17/what-is-script-error)

方法②：
    从这篇文章中得出，如果用try-catch包住了代码，在catch（e）中拿到的e是完整的，可以在catch里面发送报错信息。这就解释了为什么没有crossorigin 也能拿到报错信息。其实这些工作在引入sentry之后，sentry都帮我们做了。

说到try-catch，其实try-catch只能捕捉同步运行错误（async await中的错误是可以获取的），对语法和异步错误却无能为力。sentry为了能让我们捕捉到异步错误，在setTimeout、setInterval、requestAnimationFrame等回调函数上包装了一层try-catch，这样就能获取到异步回调中的运行错误了

##### 2、资源加载异常，触发的是img 或者 script元素的onerror事件，不会冒泡到window上。使用addEventListener可以获取资源加载错误 addEventListener

```javascript
window.onerror = function(message, source, lineno, colno, error) {
    // ... 
    return true; // 异常不继续冒泡，浏览器默认打印机制就会取消 
}
// 注意window的错误事件参数和element的错误参数不一致
 element.onerror = function(event) {
     // ... 
}
```

##### 3、无法捕捉promise抛出的错误。使用addEventListener可以获取unhandledrejection错误。

##### 4、不同浏览器异常信息支持不同，异常的堆栈不统一。

## 二.window.addEventListener

```javascript
window.addEventListener('error', function(event) { 
    //... 
})
```

#### window.addEventListener存在的问题:
 错误信息没有onerorr全面

#### 优势

也就是window.onerror的劣势

1. 可以获取资源加载错误 addEventListener('error', callback, true)
2. 可以通过addEventListener事件获取promise错误

```javascript
window.addEventListener('unhandledrejection',(e) => { 
     e.preventDefault()   //   去掉控制台的红色报错  
})
```
